### ISSUE TITLE
[Question] Base Image Address?

### ISSUE THREAD

**Issue by ohaddahan** [AppsusUK/NFT-Art-Generator#10]
What is that? How to use it?

**Comment by AppsusUK** [comment]
The Base image address can be used to replace all the empty "image" properties in the generated metadata json files.

It can be used by doing the following:
1. Generate images and metadata as normal (generated metadata at this stage has an empty "image" property)
2. Once generated, you need your IPFS link or image link e.g. "ipfs://CID_HERE" or "https://url_to_images" and add it to the input field
3. Click the "+" button and select the output metadata folder and the app will add the base image address + / + the file name + .png e.g. ifps://CID_HERE/1.png to 1.json for each of the metadata files 
4. Your metadata is ready for uploading now as all properties should be filled in
