### ISSUE TITLE
Donations to Remove Tag in Description

### ISSUE THREAD

**Issue by LiamKenyon** [AppsusUK/NFT-Art-Generator#2]
First of all great little tool.

Is it possible to setup something in future for donation etc... to remove the credit in description of the metadata?

As I assume someone creating alot of NFTs would find that annoying etc...

Ability to set own description for a donation etc...

**Comment by AppsusUK** [comment]
Hi thanks for the feedback, the description will be editable in a coming update. You won't need to donate or pay for any of the features!
