### ISSUE TITLE
Disallow Duplication

### ISSUE THREAD

**Issue by LiamKenyon** [AppsusUK/NFT-Art-Generator#3]
An option to tick/untick allowing duplicates. After a brief run duplicates are created before all possible options are done.

**Comment by AppsusUK** [comment]
Yes an option to allow duplicates can be added, thank you for the suggestion it's been noted!

**Comment by AbdulDridi** [comment]
> An option to tick/untick allowing duplicates. After a brief run duplicates are created before all possible options are done.

Hey Liam, just to confirm, you're saying that you're seeing duplicates being generated? This shouldn't really be happening as we currently dissalow duplication, so this would be a bug!

Any chance you could provide a reproducable test case/steps to reproduce duplication?

I also want to confirm that the duplication was seen on a single generation run, as every generation batch is currently independent and if performed directly after another, will overwite the generated files.

Thanks for the report!

**Comment by LiamKenyon** [comment]
Hi, yeah I had duplicates created while doing a test run off 50 generated.

I will try and reproduce it again later and see if I can record.

I had 5 image layers and 3 (common, legendary & rare) levels.

**Comment by AbdulDridi** [comment]
> Hi, yeah I had duplicates created while doing a test run off 50 generated.
> 
> I will try and reproduce it again later and see if I can record.
> 
> I had 5 image layers and 3 (common, legendary & rare) levels.

Thanks, that would be awesome, I couldn't find an obvious place in which the duplication occurs, so having a solid example would narrow it down super quickly

One question I do have though, for the duplicate images you were seeing, were you sharing any image files between the common, legendary & rare folders you have?

I.e.
Layer
Background 
|
|Rarity Folders
|---Common
|---|---black.png
|     
|---Legendary
|---|---black.png
|
|---Rare
|---|---black.png

Where all black.pngs looked the same? (our program would say they are different files)
