### ISSUE TITLE
Ability to set Info for JSON file

### ISSUE THREAD

**Issue by LiamKenyon** [AppsusUK/NFT-Art-Generator#7]
Would be awesome to have the ability to set info for the JSON file so matches the Metaplex Solana NFT Standard, main ones are in bold below:

Also it would be good if the images started at 0.png/json as per the requirements and not 1.png/json etc...

Example Below:
`{
  "name": "Solflare X NFT",
  "symbol": "",
  "description": "Celebratory Solflare NFT for the Solflare X launch",
  **"seller_fee_basis_points": 0,**
....
  "attributes": [
....
  },
  "properties": {
    "files": [
....
    ],
    "category": "video",
    "creators": [
      {
        **"address": "SOLFLR15asd9d21325bsadythp547912501b",**
        **"share": 100**
      }
    ]
  }
}`

More Info: https://docs.metaplex.com/nft-standard

**Comment by AppsusUK** [comment]
Hey thanks for the feedback, I've just pushed an update that allows more options for the metadata customization, which covers the relevant properties from above.

Starting from 0 is not a requirement (tested both on OpenSea and SolSea and everything works fine). Correct me if I'm wrong but this is preference and thus might be added in a future release as I don't want to make it too confusing for new users with too many options as the app is new.

Closing as will be updated in build version 0.0.5
